// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBok8a8ecwcBQbFWJe1cGewXFbAJaohQjA',
    appId: '1:527161473297:web:7ca7cb2df407cc94d3f4b0',
    messagingSenderId: '527161473297',
    projectId: 'diplomna-rabota-488d4',
    authDomain: 'diplomna-rabota-488d4.firebaseapp.com',
    storageBucket: 'diplomna-rabota-488d4.appspot.com',
    measurementId: 'G-NFP738PNZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5v8Jp3Vb6rZXIAg_pJrecimFd-Ur6deQ',
    appId: '1:527161473297:android:2eb99086429f37b6d3f4b0',
    messagingSenderId: '527161473297',
    projectId: 'diplomna-rabota-488d4',
    storageBucket: 'diplomna-rabota-488d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6S48PF4bZpksiKpgm9E5_SFpWqK3ofo0',
    appId: '1:527161473297:ios:dd38282241234beed3f4b0',
    messagingSenderId: '527161473297',
    projectId: 'diplomna-rabota-488d4',
    storageBucket: 'diplomna-rabota-488d4.appspot.com',
    iosClientId: '527161473297-b35rcva13ia1f6vqqah4babdpu0bit9i.apps.googleusercontent.com',
    iosBundleId: 'org.elsys.listApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6S48PF4bZpksiKpgm9E5_SFpWqK3ofo0',
    appId: '1:527161473297:ios:dd38282241234beed3f4b0',
    messagingSenderId: '527161473297',
    projectId: 'diplomna-rabota-488d4',
    storageBucket: 'diplomna-rabota-488d4.appspot.com',
    iosClientId: '527161473297-b35rcva13ia1f6vqqah4babdpu0bit9i.apps.googleusercontent.com',
    iosBundleId: 'org.elsys.listApp',
  );
}
