name: list_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.1.3
  firebase_core: ^2.4.1
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6+1
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
